# Generated by Django 4.2.10 on 2024-02-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_testimonialrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonialrequest',
            old_name='name',
            new_name='username',
        ),
    ]
