# Generated by Django 4.2.10 on 2024-02-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_rename_name_testimonialrequest_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialRequest',
        ),
    ]
