# Generated by Django 4.2.10 on 2024-02-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0006_collaboraterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='TestimonialRequest',
        ),
    ]
